# Generated by Django 5.0 on 2024-11-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Names', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('Organization', models.CharField(max_length=50)),
                ('Occupation', models.CharField(max_length=50)),
                ('Quote', models.CharField(max_length=150)),
                ('DateT', models.DateTimeField()),
                ('Event', models.CharField(default='National ICT Innovation Hub, Nakawa', max_length=250)),
                ('Location', models.CharField(default='8JH7+PQ Kampala', max_length=250)),
            ],
        ),
    ]
