# Generated by Django 5.0 on 2024-11-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocket', '0002_alter_cadets_datet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadets',
        ),
    ]
