# Generated by Django 5.0 on 2024-11-21 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moonrocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadets',
            name='DateT',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 12, 24, 39, 82411)),
        ),
    ]
