# Generated by Django 5.2.6 on 2025-09-20 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moonrocks', '0002_alter_cadets_datet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadets',
            name='Email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cadets',
            name='image',
            field=models.ImageField(null=True, upload_to='{% static /img %}'),
        ),
        migrations.AlterField(
            model_name='cadets',
            name='DateT',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 20, 12, 16, 26, 450941)),
        ),
    ]
